version: '3.2'

services:
  kafka-producer:
    image: payamyprojects.com/kafka-python-producer:0.0.1
    volumes:
      - "./producer/main.py:/main.py"
    command: >
      sh -c "python /main.py"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      placement: 
        constraints: 
          - node.role == manager

  kafka-0:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data_0:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=0
    # depends_on:
    #   - zookeeper
    deploy:
      placement: 
        constraints: 
          - node.role == manager

  kafka-1:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9094:9094"
      - "9095:9095"
    volumes:
      - "kafka_data_1:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9094,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=1
    # depends_on:
    #   - zookeeper
    deploy:
      placement: 
        constraints: 
          - node.role == worker


volumes:
  zookeeper_data:
    driver: local
  kafka_data_0:
    driver: local
  kafka_data_1:
    driver: local
